# Generated by Django 6.0.3 on 2026-03-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('event_code', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_number', models.IntegerField(unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rookie_year', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('motto', models.TextField(blank=True, null=True)),
                ('gmaps_url', models.URLField(blank=True, max_length=500, null=True)),
                ('gmaps_place_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['team_number'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('match_number', models.IntegerField()),
                ('comp_level', models.CharField(max_length=10)),
                ('score_red', models.IntegerField(blank=True, null=True)),
                ('score_blue', models.IntegerField(blank=True, null=True)),
                ('predicted_time', models.IntegerField(blank=True, null=True)),
                ('actual_time', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='match.event')),
                ('blue_teams', models.ManyToManyField(related_name='blue_matches', to='match.team')),
                ('red_teams', models.ManyToManyField(related_name='red_matches', to='match.team')),
            ],
            options={
                'ordering': ['match_number'],
            },
        ),
    ]
