# Generated by Django 6.0.3 on 2026-03-20 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_event_city_event_end_date_event_event_type_string_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPeriodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('auto', 'Autonomous'), ('p1', 'Tele-op 1'), ('p2', 'Tele-op 2'), ('p3', 'Tele-op 3'), ('p4', 'Tele-op 4'), ('p5', 'Tele-op 5'), ('p6', 'Tele-op 6')], max_length=10)),
                ('score_value', models.IntegerField(default=0)),
                ('defended', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_data', to='match.matchscoutreport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.team')),
            ],
            options={
                'unique_together': {('report', 'team', 'phase')},
            },
        ),
    ]
