# Generated by Django 6.0.3 on 2026-03-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_matchscoutreport_teamperioddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['predicted_time', 'match_number']},
        ),
    ]
