# Generated by Django 6.0.3 on 2026-03-20 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['sequence', 'match_number']},
        ),
        migrations.AddField(
            model_name='match',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchscoutreport',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='match.match'),
        ),
    ]
