# Generated by Django 6.0.3 on 2026-03-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_options_match_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamperioddata',
            name='alliance_share',
            field=models.FloatField(default=0.0),
        ),
    ]
